version: '3'

services:
  node:
    image: 'node:10.1.0-alpine'
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/node/app
    entrypoint: "npm"
    command: "start"
    environment:
      - google_cse_id
      - google_api_key
